/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Dragon Ball Z: Ultimate Battle 22)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800F24CCu
#define func_800F24CC BootEntry  /* alias */
